//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsVirtualDesktopHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowPrevNextIcons {
            get {
                return ((bool)(this["ShowPrevNextIcons"]));
            }
            set {
                this["ShowPrevNextIcons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartupWithWindows {
            get {
                return ((bool)(this["StartupWithWindows"]));
            }
            set {
                this["StartupWithWindows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowOverlay {
            get {
                return ((bool)(this["ShowOverlay"]));
            }
            set {
                this["ShowOverlay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OverlayAnimate {
            get {
                return ((bool)(this["OverlayAnimate"]));
            }
            set {
                this["OverlayAnimate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OverlayTranslucent {
            get {
                return ((bool)(this["OverlayTranslucent"]));
            }
            set {
                this["OverlayTranslucent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClickDesktopNumberOpensTaskView {
            get {
                return ((bool)(this["ClickDesktopNumberOpensTaskView"]));
            }
            set {
                this["ClickDesktopNumberOpensTaskView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("medium")]
        public string OverlayDuration {
            get {
                return ((string)(this["OverlayDuration"]));
            }
            set {
                this["OverlayDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("middlecenter")]
        public string OverlayPosition {
            get {
                return ((string)(this["OverlayPosition"]));
            }
            set {
                this["OverlayPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OverlayShowOnAllMonitors {
            get {
                return ((bool)(this["OverlayShowOnAllMonitors"]));
            }
            set {
                this["OverlayShowOnAllMonitors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowDesktopNameInitial {
            get {
                return ((bool)(this["ShowDesktopNameInitial"]));
            }
            set {
                this["ShowDesktopNameInitial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseHotKeysToJumpToDesktop {
            get {
                return ((bool)(this["UseHotKeysToJumpToDesktop"]));
            }
            set {
                this["UseHotKeysToJumpToDesktop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt")]
        public string HotKeysToJumpToDesktop {
            get {
                return ((string)(this["HotKeysToJumpToDesktop"]));
            }
            set {
                this["HotKeysToJumpToDesktop"] = value;
            }
        }

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool UseHotKeyToJumpToMostRecentDesktop {
			get {
				return ((bool)(this["UseHotKeyToJumpToMostRecentDesktop"]));
			}
			set {
				this["UseHotKeyToJumpToMostRecentDesktop"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt")]
        public string HotKeysToJumpToMostRecentDesktop {
            get {
                return ((string)(this["HotKeysToJumpToMostRecentDesktop"]));
            }
            set {
                this["HotKeysToJumpToMostRecentDesktop"] = value;
            }
        }
    }
}
